### ISSUE TITLE
Help with putting single cycle on HW

### ISSUE THREAD

**Issue by diracpulse** [vittorioserra/cpu_vhdl#2]
All seems done, just the LEDs are not lighting. Probably we are not loading the program correctly into memory.
YOUR HELP IS NEEDED. Please let's put this on the hardware. @CeDoMain

**Comment by CeDoMain** [comment]
Changed the led control to be fully asyncron:
![image](https://github.com/vittorioserra/cpu_vhdl/assets/9774882/73d330af-63a4-4cc2-af2f-90c4e3c0e5ca)

Does the cpu execute correctly?

**Comment by CeDoMain** [comment]
You use an old make script which do not set the project_path generic. I will update your branch.

**Comment by CeDoMain** [comment]
Simulation now works:
![image](https://github.com/vittorioserra/cpu_vhdl/assets/9774882/d41c4039-269f-4958-8fc5-189e64d0344f)

https://github.com/vittorioserra/cpu_vhdl/tree/single_cycle_cpu
Has the actual working fileset. Make sure to sycronize your remotes. Rerun make.tcl.
