### ISSUE TITLE
Rewriting decoder with carve out functions?

### ISSUE THREAD

**Issue by CeDoMain** [vittorioserra/cpu_vhdl#4]
In reply to your comment:
-- PLEASE REWRITE WITH CARVE OUT FUCNTIONS; IT IS CLEANER THAT WAY !!! If you miss a bit here you are FUCKED!!!

I totally understand that the **local readability** (instruction specific) is better if I use if-elsif statements to filter out the different instructions! I have made some observations which let me think that the case? approach is for the **global readability** better:
- I made heavy use of multicursor to write and edit. This way i do not have to copy and paste the code for one instruction decode and made copy-paste-errors. Parallel edit (multicursor) seems to me way less error prone than sequencial edit (copy-paste blocks).
- Because I can see the whole case structure I am able to implicitly detect error-patterns (missing bits, missing signal assignments). I am not able to detect this in code which lays out in hundreds of lines where I can see only 50 of them simultaneously.
- The bit patterns are directly copied from the table in the specs.

Whats your thoughts about that?

**Comment by CeDoMain** [comment]
- VS Code also allows me to select a tag (like "i_rs1__imm" or "0010011") and marks me the same occasions in the file. This way I can also detect wrong patterns.

**Comment by diracpulse** [comment]
Hi, just a cuple of notes : 

VSCode is shit. All from microsoft is shit. I do not use it, and such features are not standard in all editors. Keep in mind, you should have to be able to do a quickfix with vim.

It is not only about reeadibility but also about reliabilty. Carve out functions might be cumbersome (e.g., I could pack them all in a single mega instruction) but that us exactely the way to make as low errors as possible, especially when making the ISA bigger.
